apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::536749675593:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-5A46thSLFgk1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::536749675593:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2023-10-15T21:46:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1234"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 819451ca-dab5-4c3f-b993-9b0bf0bf9e70
